apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "paintme-traffic.fullname" . }}
  labels:
    {{- include "paintme-traffic.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
#   - port:
#       number: 443
#       name: https
#       protocol: HTTPS
#     hosts:
#     - "*"