apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include "paintme-traffic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "paintme-traffic.appSelectorLabels" . | nindent 4 }}
